name: dsa
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.8
  - numpy>=1.19.1
  - pandas>=1.1.2
  - requests
  - colored
  - dictdiffer
  - pip:
      - pyactionnetwork
      - uszipcode
      - -e .
